# This is a basic workflow to help you get started with Actions

name: LibreOffice Daily, no bundled help

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build AppImage
        run: ./make_libreoffice_appimage daily x86-64 N N Y N N
      - name: Get version
        id: ver
        run: echo "::set-output name=version::$(cat .version)"
        
     
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "out/*.AppImage"
          tag: ${{ steps.ver.outputs.version}}
          token: ${{ secrets.GITHUB_TOKEN }}
